### Site Settings ###
title               : Daniel Klevebring
description         : >-
                      Staff Machine Learning Engineer at Epidemic Sound.
                      Building agentic discovery systems and search.
baseurl             : ""
url                 : "https://dakl.github.io"
remote_theme        : yousinix/portfolYOU
open_new_tab        : true


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Daniel Klevebring
  image             : /images/me.png
  email             : daniel.klevebring@gmail.com
  github            : dakl
  linkedin          : daniel-klevebring-87333b2


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - LICENSE
  - "*.log"
